### ISSUE TITLE
Explore Replacing Custom Data Query with CEL

### ISSUE THREAD

**Issue by naveensrinivasan** [bitbomdev/minefield#59]
#### Description
We currently use a custom data query language to query dependencies and dependents within our graph. While functional, this custom solution requires ongoing maintenance and lacks the flexibility and robustness of established query languages. To improve maintainability, security, and flexibility, we propose exploring the replacement of our custom data query language with [CEL (Common Expression Language)](https://github.com/google/cel-spec).

#### Reasons for Exploration

1. **Standardization**:
   - **Custom Solution**: Our custom query language is unique to our system, which means new developers need to spend time learning it. This can slow down onboarding and increase the risk of misinterpretation.
   - **CEL**: CEL is a well-documented and widely-used expression language. Adopting CEL would leverage existing knowledge and resources, reducing the learning curve for new developers.

2. **Security**:
   - **Custom Solution**: Custom query languages can have hidden security vulnerabilities, especially if not rigorously tested. Ensuring the security of a custom solution requires significant effort and expertise.
   - **CEL**: CEL is designed with security in mind and is used in various environments, including security-sensitive applications. It has built-in features to prevent common security issues, reducing the risk of vulnerabilities.

3. **Flexibility**:
   - **Custom Solution**: Extending the capabilities of our custom query language requires additional development and testing. This can be time-consuming and may introduce bugs.
   - **CEL**: CEL supports many expressions and can be easily extended to support custom functions. This flexibility allows us to handle more complex queries without significant additional development.

4. **Maintenance**:
   - **Custom Solution**: Maintaining a custom query language involves ongoing development to fix bugs, add features, and ensure compatibility with other system parts. This can be resource-intensive.
   - **CEL**: By leveraging an external library like CEL, we can reduce the burden of maintaining a custom solution. The CEL community actively maintains and updates the library, ensuring it remains robust and up-to-date.

5. **Performance**:
   - **Custom Solution**: Optimizing the performance of a custom query language requires in-depth knowledge and continuous effort. Performance issues can be challenging to diagnose and resolve.
   - **CEL**: CEL is optimized for performance and can handle complex queries efficiently. Using CEL can improve the performance of our query operations, especially for large datasets.

6. **Community and Ecosystem**:
   - **Custom Solution**: Our custom query language is isolated from the broader developer community. This limits the availability of external tools, libraries, and community support.
   - **CEL**: CEL has a vibrant community and ecosystem. By adopting CEL, we can benefit from community support, third-party tools, and integrations that can enhance our system's capabilities.

#### Example: Using CEL for Querying Dependencies and Dependents

To illustrate how CEL can provide a similar experience to our custom query language, let's consider an example where we query dependencies and dependents of nodes in our graph.

**Current Custom Query Example**:
```sh
minefield query "dependencies library pkg:generic/dep1@1.0.0 and dependents library pkg:generic/lib-A@1.0.0"
```

**Equivalent CEL Query Example**:
1. **Define the CEL Environment**:
   - We need to define the variables and functions CEL will use to evaluate the query.

2. **Evaluate the CEL Expression**:
   - We compile and evaluate the CEL expression using the defined environment and input variables.

**Conceptual Example**:
- **CEL Environment**: Define variables for `dependencies` and `dependents`.
- **CEL Expression**: `dependencies.exists(d, d == "pkg:generic/dep1@1.0.0") && dependents.exists(d, d == "pkg:generic/lib-A@1.0.0")`
- **Input Variables**: Lists of strings representing the dependencies and dependents.

**Explanation**:
- The CEL environment is set up with variables for `dependencies` and `dependents`.
- The CEL expression checks if a node depends on "pkg:generic/dep1@1.0.0" and a dependent of "pkg:generic/lib-A@1.0.0".
- The input variables are provided as lists of strings representing the dependencies and dependents.

This approach demonstrates how CEL can perform complex queries similar to our custom query language while providing the benefits of standardization, security, flexibility, and maintainability.

#### Conclusion
Exploring the use of CEL will help us determine if it can enhance our system's maintainability, security, and flexibility. We should evaluate CEL and develop a prototype to assess its suitability for our needs.

#### References
- [CEL GitHub Repository](https://github.com/google/cel-spec)
- [CEL Go Implementation](https://github.com/google/cel-go)

**Comment by neilnaveen** [comment]
Closing in favor of https://github.com/alecthomas/participle
